delete jogos;
DBCC CHECKIDENT ('dbo.Jogos', RESEED, 0);
GO
SET IDENTITY_INSERT [dbo].[Jogos] ON
INSERT INTO [dbo].[Jogos] ([JogoId], [Titulo], [Desc], [Capa], [DataLancamento], [Genero], [Empresa], [Editor]) VALUES (1, N'Grand Theft Auto V', N'Grand Theft Auto V é um jogo eletrônico de ação-aventura desenvolvido pela Rockstar North e publicado pela Rockstar Games. É o sétimo título principal da série Grand Theft Auto e foi lançado originalmente em 17 de setembro de 2013 para PlayStation 3 e Xbox 360, com remasterizações lançadas em 2014 para PlayStation 4 e Xbox One, em 2015 para Microsoft Windows e em 2021 para PlayStation 5 e Xbox Series X. O jogo se passa no estado ficcional de San Andreas, com a história da campanha um jogador seguindo três criminosos e seus esforços para realizarem assaltos sob a pressão de uma agência governamental. O mundo aberto permite que os jogadores naveguem livremente pelas áreas rurais e urbanas de San Andreas.', N'/assets/images/capa_gtav.png', N'2013-09-17 00:00:00', N'Ação e Aventura', N'Rockstar North', N'Rockstar Games')
INSERT INTO [dbo].[Jogos] ([JogoId], [Titulo], [Desc], [Capa], [DataLancamento], [Genero], [Empresa], [Editor]) VALUES (2, N'Star Wars Battlefront II', N'Star Wars Battlefront II é um jogo de ação de tiro em primeira e terceira pessoa, baseado na franquia Star Wars em desenvolvimento pela DICE, em colaboração com a Criterion Games e Motive Studios e publicado pela Electronic Arts.', N'/assets/images/capa_stw_battlefront2.png', N'2017-11-17 00:00:00', N'Ação e Aventura', N'DICE', N'EA')
INSERT INTO [dbo].[Jogos] ([JogoId], [Titulo], [Desc], [Capa], [DataLancamento], [Genero], [Empresa], [Editor]) VALUES (3, N'Batman Arkham Knight', N'Batman: Arkham Knight é um jogo eletrônico de ação-aventura produzido pela Rocksteady Studios e lançado mundialmente 23 de Junho de 2015 pela Warner Bros. Interactive Entertainment para PlayStation 4, Xbox One e Microsoft Windows. Baseado no popular super-herói da DC Comics, Batman, é o sucessor do jogo de 2013 Batman: Arkham Origins, e o quarto e último jogo da série Batman: Arkham. Arkham Knight foi o primeiro da série que teve a classificação "M" (Maiores de 17 anos) atribuída pela ESRB. Estava planejada uma versão para os sistemas OS X e Linux, mas foi cancelada em fevereiro de 2016.

Escrita por Sefton Hill, Martin Lancaster e Ian Ball, a história acontece um ano depois dos eventos de Arkham City, em que Batman, no pico máximo das suas habilidades, tem de defrontar o super-vilão Espantalho, que criou um ataque a Gotham City causando a evacuação da cidade. Com a ajuda do misterioso Cavaleiro de Arkham, um personagem original criado pela Rocksteady para o jogo, Espantalho reúne os grandes inimigos de Batman, com o intuito de eliminar de uma vez o Cavaleiro das Trevas.', N'/assets/images/capa_batman_arkham_knight.png', N'2015-06-23 00:00:00', N'Ação e Aventura', N'Rocksteady', N'Warner Bros')
SET IDENTITY_INSERT [dbo].[Jogos] OFF
